workflows:
  # WORKFLOW 1: APP ANDROID
  app-android-workflow:
    name: App - Android Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play_credentials
      flutter: stable
    working_directory: app
    scripts:
      - name: Get dependencies (shared + app)
        script: |
          cd ../shared && flutter pub get
          cd ../app && flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release --build-number=$BUILD_NUMBER
    artifacts:
      - app/build/app/outputs/bundle/release/*.aab

  # WORKFLOW 2: APP IOS
  app-ios-workflow:
    name: App - iOS Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials
      flutter: stable
      xcode: latest
    working_directory: app
    scripts:
      - name: Get dependencies (shared + app)
        script: |
          cd ../shared && flutter pub get
          cd ../app && flutter pub get
      - name: Install Pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --build-number=$BUILD_NUMBER
    artifacts:
      - app/build/ios/ipa/*.ipa

  # WORKFLOW 3: APP WEB
  app-web-workflow:
    name: App - Web Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    working_directory: app
    scripts:
      - name: Get dependencies (shared + app)
        script: |
          cd ../shared && flutter pub get
          cd ../app && flutter pub get
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - app/build/web/**

  # WORKFLOW 4: ADMIN WEB
  admin-web-workflow:
    name: Admin - Web Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    working_directory: admin
    scripts:
      - name: Get dependencies (shared + admin)
        script: |
          cd ../shared && flutter pub get
          cd ../admin && flutter pub get
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - admin/build/web/**