-- ============================================================
-- MIGRAÇÃO COMPLETA — Castanhal HUB Admin
-- Execute no SQL Editor do Supabase (uma única vez)
-- ============================================================

-- ============================================================
-- 1. EXTENSÕES
-- ============================================================
-- Habilita o PostGIS para cálculos geográficos (busca por proximidade)
create extension if not exists postgis;

-- Habilita pgcrypto para gen_random_uuid()
create extension if not exists "pgcrypto";

-- ============================================================
-- 2. ENUMS
-- ============================================================
-- Define os tipos de cliques permitidos para analytics
do $$ begin
  create type click_event_type as enum('whatsapp', 'instagram', 'phone', 'website');
exception
  when duplicate_object then null;
end $$;

-- ============================================================
-- 3. TABELAS
-- ============================================================

-- ----------------------------------------------------------
-- 3.1 Categorias
-- ----------------------------------------------------------
-- NOTA: categories.id é UUID para consistência com businesses.id
-- e compatibilidade com o tipo String no Dart (Supabase Flutter)
create table if not exists categories (
  id UUID default gen_random_uuid() primary key,
  name TEXT not null unique,
  icon_name TEXT not null, -- Nome do ícone (ex: 'restaurant', 'shopping_bag')
  created_at TIMESTAMPTZ default NOW()
);

-- ----------------------------------------------------------
-- 3.2 Negócios (Businesses)
-- ----------------------------------------------------------
create table if not exists businesses (
  id UUID default gen_random_uuid() primary key,
  category_id UUID references categories(id) on delete set null,
  name TEXT not null,
  description TEXT,
  address TEXT,
  whatsapp_number TEXT,
  instagram_url TEXT,
  image_url TEXT, -- antigo street_view_image_url
  is_premium BOOLEAN default false,
  rating DECIMAL(3, 2) default 0 check (rating >= 0 and rating <= 5),

  -- Geolocalização
  latitude FLOAT8,
  longitude FLOAT8,

  -- Coluna calculada para PostGIS (facilita buscas por raio de distância)
  -- Nota: será NULL se latitude ou longitude forem NULL
  location GEOGRAPHY(POINT, 4326) GENERATED ALWAYS as (
    case
      when latitude is not null and longitude is not null
        then ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::GEOGRAPHY
      else null
    end
  ) STORED,

  created_at TIMESTAMPTZ default NOW(),
  updated_at TIMESTAMPTZ default NOW()
);

-- ----------------------------------------------------------
-- 3.3 Analytics
-- ----------------------------------------------------------
create table if not exists analytics_clicks (
  id BIGINT generated by default as identity primary key,
  business_id UUID references businesses(id) on delete cascade,
  click_type click_event_type not null,
  created_at TIMESTAMPTZ default NOW()
);

-- ============================================================
-- 4. MIGRAÇÃO DE COLUNA: street_view_image_url -> image_url
-- ============================================================
-- Se a tabela já existe com o nome antigo, renomeia
do $$ begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'businesses' and column_name = 'street_view_image_url'
  ) then
    alter table businesses rename column street_view_image_url to image_url;
  end if;
end $$;

-- Se a coluna image_url não existir de jeito nenhum (tabela antiga sem a coluna), cria
do $$ begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'businesses' and column_name = 'image_url'
  ) then
    alter table businesses add column image_url text;
  end if;
end $$;

-- ============================================================
-- 5. TRIGGER: updated_at
-- ============================================================
create or replace function set_updated_at()
returns trigger as $$
begin
  NEW.updated_at = NOW();
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trg_businesses_updated_at on businesses;
create trigger trg_businesses_updated_at
  before update on businesses
  for each row
  execute function set_updated_at();

-- Habilita extensão para trigram (busca textual difusa) — DEVE vir antes dos índices GIN
create extension if not exists pg_trgm;

-- ============================================================
-- 6. ÍNDICES (Otimização)
-- ============================================================
create index if not exists idx_businesses_category on businesses (category_id);
create index if not exists idx_businesses_premium_rating on businesses (is_premium desc, rating desc);
create index if not exists idx_businesses_location on businesses using GIST (location);
create index if not exists idx_businesses_name_trgm on businesses using GIN (name gin_trgm_ops);
create index if not exists idx_analytics_clicks_business on analytics_clicks (business_id);
create index if not exists idx_analytics_clicks_created on analytics_clicks (created_at desc);
create index if not exists idx_analytics_clicks_type on analytics_clicks (click_type);

-- ============================================================
-- 7. ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Habilita RLS em todas as tabelas
alter table categories enable row level security;
alter table businesses enable row level security;
alter table analytics_clicks enable row level security;

-- Remove políticas antigas para evitar duplicatas
drop policy if exists "Leitura pública de categorias" on categories;
drop policy if exists "Escrita apenas por admin autenticado" on categories;
drop policy if exists "Leitura pública de negócios" on businesses;
drop policy if exists "Escrita apenas por admin autenticado" on businesses;
drop policy if exists "Qualquer um pode registrar cliques" on analytics_clicks;
drop policy if exists "Apenas admin vê analytics" on analytics_clicks;

-- ----------------------------------------------------------
-- 7.1 Políticas para CATEGORIES
-- ----------------------------------------------------------
create policy "Leitura pública de categorias"
  on categories for select
  using (true);

create policy "Inserção apenas por admin autenticado"
  on categories for insert
  to authenticated
  with check (true);

create policy "Atualização apenas por admin autenticado"
  on categories for update
  to authenticated
  using (true)
  with check (true);

create policy "Exclusão apenas por admin autenticado"
  on categories for delete
  to authenticated
  using (true);

-- ----------------------------------------------------------
-- 7.2 Políticas para BUSINESSES
-- ----------------------------------------------------------
create policy "Leitura pública de negócios"
  on businesses for select
  using (true);

create policy "Inserção apenas por admin autenticado"
  on businesses for insert
  to authenticated
  with check (true);

create policy "Atualização apenas por admin autenticado"
  on businesses for update
  to authenticated
  using (true)
  with check (true);

create policy "Exclusão apenas por admin autenticado"
  on businesses for delete
  to authenticated
  using (true);

-- ----------------------------------------------------------
-- 7.3 Políticas para ANALYTICS
-- ----------------------------------------------------------
create policy "Qualquer um pode registrar cliques"
  on analytics_clicks for insert
  with check (true);

create policy "Apenas admin vê analytics"
  on analytics_clicks for select
  to authenticated
  using (true);

-- ============================================================
-- 8. VIEW DE FEED (Ranking)
-- ============================================================
-- Ordena primeiro os Premium e depois pela melhor nota
drop view if exists get_feed cascade;
create view get_feed as
select
  b.id,
  b.name,
  b.description,
  b.is_premium,
  b.rating,
  b.whatsapp_number,
  b.instagram_url,
  b.image_url,
  b.latitude,
  b.longitude,
  b.category_id,
  c.name as category_name,
  c.icon_name as category_icon
from businesses b
left join categories c on b.category_id = c.id
order by b.is_premium desc, b.rating desc;

-- ============================================================
-- 9. FUNÇÕES
-- ============================================================

-- ----------------------------------------------------------
-- 9.1 Busca por Proximidade (Raio em metros)
-- Exemplo de uso: RPC no Supabase chamando 'get_nearby_businesses'
-- ----------------------------------------------------------
create or replace function get_nearby_businesses(
  lat float8,
  lng float8,
  radius_meters int
)
returns setof get_feed
language sql
stable
as $$
  select gf.*
  from get_feed gf
  join businesses b on b.id = gf.id
  where b.location is not null
    and ST_DWithin(
          ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography,
          b.location,
          radius_meters
        )
  order by gf.is_premium desc, gf.rating desc;
$$;

-- ----------------------------------------------------------
-- 9.2 Função auxiliar: total de cliques por período
-- ----------------------------------------------------------
create or replace function get_click_stats(
  since timestamptz default now() - interval '30 days'
)
returns table (
  click_type text,
  total_clicks bigint
)
language sql
stable
as $$
  select ac.click_type::text, count(*)::bigint as total_clicks
  from analytics_clicks ac
  where ac.created_at >= since
  group by ac.click_type
  order by total_clicks desc;
$$;

-- ============================================================
-- 10. CATEGORIAS — Sementes (Seed)
-- ============================================================
insert into categories (name, icon_name) values
  ('Alimentação',       'restaurant'),
  ('Compras',           'shopping_bag'),
  ('Serviços',          'build'),
  ('Saúde & Beleza',    'spa'),
  ('Educação',          'school'),
  ('Lazer & Entretenimento', 'sports_esports'),
  ('Hospedagem',        'hotel'),
  ('Automotivo',        'directions_car'),
  ('Imobiliário',       'real_estate_agent'),
  ('Tecnologia',        'computer'),
  ('Moda & Acessórios', 'checkroom'),
  ('Agro & Negócios',   'agriculture')
on conflict (name) do nothing;

-- ============================================================
-- 11. STORAGE — Bucket para imagens dos negócios
-- ============================================================

-- Cria bucket público para imagens
insert into storage.buckets (id, name, public, avif_autodetection)
values ('business-images', 'business-images', true, false)
on conflict (id) do nothing;

-- Remove políticas antigas do bucket
drop policy if exists "Imagens públicas" on storage.objects;
drop policy if exists "Upload por admin autenticado" on storage.objects;
drop policy if exists "Delete por admin autenticado" on storage.objects;

-- Política: qualquer um pode ver imagens
create policy "Imagens públicas"
on storage.objects for select
using (bucket_id = 'business-images');

-- Política: apenas admin autenticado pode fazer upload
create policy "Upload por admin autenticado"
on storage.objects for insert
to authenticated
with check (bucket_id = 'business-images');

-- Política: apenas admin autenticado pode atualizar
create policy "Update por admin autenticado"
on storage.objects for update
to authenticated
using (bucket_id = 'business-images')
with check (bucket_id = 'business-images');

-- Política: apenas admin autenticado pode deletar
create policy "Delete por admin autenticado"
on storage.objects for delete
to authenticated
using (bucket_id = 'business-images');

-- ============================================================
-- FIM DA MIGRAÇÃO
-- ============================================================
